MovieReservation/MovieReservation/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieReservation.Models;

namespace MovieReservation.Controllers
{
    public class MoviesController : Controller
    {
        private ReservationModelContainer db = new ReservationModelContainer();

        // GET: Movies
        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Movie_Id,Movie_Name,Time,Director,Synopsis,Rate,Genre,Release_date,Movie_Photo")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Movie_Id,Movie_Name,Time,Director,Synopsis,Rate,Genre,Release_date,Movie_Photo")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieReservation/MovieReservation/Controllers/TimeSchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieReservation.Models;

namespace MovieReservation.Controllers
{
    public class TimeSchedulesController : Controller
    {
        private ReservationModelContainer db = new ReservationModelContainer();

        // GET: TimeSchedules
        public ActionResult Index()
        {
            var timeSchedules = db.TimeSchedules.Include(t => t.Movie).Include(t => t.Room);
            return View(timeSchedules.ToList());
        }

        // GET: TimeSchedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeSchedule timeSchedule = db.TimeSchedules.Find(id);
            if (timeSchedule == null)
            {
                return HttpNotFound();
            }
            return View(timeSchedule);
        }

        // GET: TimeSchedules/Create
        public ActionResult Create()
        {
            ViewBag.Movie_Id = new SelectList(db.Movies, "Movie_Id", "Movie_Name");
            ViewBag.Room_Id = new SelectList(db.Rooms, "Room_Id", "Type");
            return View();
        }

        // POST: TimeSchedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Schedule_Id,Time,Language,Movie_Id,Room_Id")] TimeSchedule timeSchedule)
        {
            if (ModelState.IsValid)
            {
                db.TimeSchedules.Add(timeSchedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Movie_Id = new SelectList(db.Movies, "Movie_Id", "Movie_Name", timeSchedule.Movie_Id);
            ViewBag.Room_Id = new SelectList(db.Rooms, "Room_Id", "Type", timeSchedule.Room_Id);
            return View(timeSchedule);
        }

        // GET: TimeSchedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeSchedule timeSchedule = db.TimeSchedules.Find(id);
            if (timeSchedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.Movie_Id = new SelectList(db.Movies, "Movie_Id", "Movie_Name", timeSchedule.Movie_Id);
            ViewBag.Room_Id = new SelectList(db.Rooms, "Room_Id", "Type", timeSchedule.Room_Id);
            return View(timeSchedule);
        }

        // POST: TimeSchedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Schedule_Id,Time,Language,Movie_Id,Room_Id")] TimeSchedule timeSchedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(timeSchedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Movie_Id = new SelectList(db.Movies, "Movie_Id", "Movie_Name", timeSchedule.Movie_Id);
            ViewBag.Room_Id = new SelectList(db.Rooms, "Room_Id", "Type", timeSchedule.Room_Id);
            return View(timeSchedule);
        }

        // GET: TimeSchedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeSchedule timeSchedule = db.TimeSchedules.Find(id);
            if (timeSchedule == null)
            {
                return HttpNotFound();
            }
            return View(timeSchedule);
        }

        // POST: TimeSchedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TimeSchedule timeSchedule = db.TimeSchedules.Find(id);
            db.TimeSchedules.Remove(timeSchedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieReservation/MovieReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://use.fontawesome.com/9355de54c5.js"></script>
    <link href="https://use.fontawesome.com/9355de54c5.css" media="all" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

</head>
@{
    var id = Session["userID"];
}

<body onload="startTime()">
    <style>
        .navbar .navbar-nav {
            display: inline-block;
            float: none;
            text-align: center;
            vertical-align: top;
        }

        .navbar .navbar-collapse {
            text-align: center;
        }
    </style>
    <div class="navbar navbar-default navbar-fixed-top text-center" style="background-color:#7e0d0d; ">
        <div class="container">

            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a href='@Url.Action("Index", "Movies")'><div class="fa fa-home " style="color:white;"> <span class="font-nav" style="color:white;"> Home</span></div></a>
                    </li>
                    <li class="nav-item">
                        <a href='@Url.Action("Index", "Movies")'><div class="fa fa-film " style="color:white;"> <span class="font-nav" style="color:white;"> Movies</span></div></a>
                    </li>
                    <li class="nav-item">
                        <a href='@Url.Action("Index", "TimeSchedules")' style="border-right-style: solid; border-width: 0.5px; border-right-color:white;"><div class="fa fa-clock-o " style="color:white; "> <span class="font-nav" style="color:white;"> Time Schedules</span></div></a>
                    </li>
                    @{
                        if (Session["userID"] != null)
                        {
                            <li class="nav-item">
                                <a href="/Users/Details/@id">
                                    <div class="fa  fa-user" style="color:white;">
                                        <span class="font-nav" style="color:white;"> @Session["username"].ToString()</span>
                                    </div>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href='@Url.Action("Index", "Users")'><div class="fa  fa-sign-in" style="color:white;"> <span class="font-nav" style="color:white;"> Sing In</span></div></a>
                            </li>
                        }
                    }
                    @{

                        if (Session["userID"] != null)
                        {
                    <li class="nav-item">
                        <a href='@Url.Action("LogOut", "Users")'><div class="fa  fa-sign-out" style="color:white;"> <span class="font-nav" style="color:white;"> Sing Out</span></div></a>
                    </li>
                        }
                    }
                </ul>

            </div>
        </div>
    </div>


    <div id="TimeNow"></div>
    @DateTime.Now.ToString(@"dd/MM/yyyy")
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();
        m = checkTime(m);
        s = checkTime(s);
        document.getElementById('TimeNow').innerHTML =
            h + ":" + m + ":" + s;
        var t = setTimeout(startTime, 500);
    }
    function checkTime(i) {
        if (i < 10) { i = "0" + i };  // add zero in front of numbers < 10
        return i;
    }
</script>